train_dataset:
  TYPE: CIFAR100
  root: /home/usr00/KDFrameworkDATA/data
  augmentations: 'configs/augmentation_configs/CIFAR100_train_aug.yaml'
  batch_size: 256
  num_workers: 8
  shuffle: True
test_dataset:
  TYPE: CIFAR100
  root: /home/usr00/KDFrameworkDATA/data
  augmentations: 'configs/augmentation_configs/CIFAR100_val_aug.yaml'
  batch_size: 512
  num_workers: 8
  shuffle: False
model:
  TYPE: ResNet
  layers: 18
settings:
  EPOCHS: &eps 200
  device: &dvc cuda
  loss_function:
    TYPE: CrossEntropyLoss
  optimizer:
    TYPE: SGD
    lr: 0.1
    momentum: 0.9
    weight_decay: 4e-5
  scheduler:
    TYPE: MultiStepLR
    milestones:
      - 60
      - 120
      - 160
    gamma: 0.1
distiller:
  TYPE: VanillaKnowledgeDistiller
  teacher:
    TYPE: ResNet
    layers: 18
  device: *dvc
  kd_loss_fucntion:
    TYPE: CrossEntropyLoss
  ALPHA: 0.5
  BETA: 0.5
  temperature: 4
logger:
  TYPE: Logger
  log_interval: 50
  checkpoint_interval: 10
  MAX_EPOCH: *eps