python train.py --config configs/APKD_ShuffleNetV2-Base-4e-5.yaml
python train.py --config configs/APKD_ShuffleNetV2-Base-5e-4.yaml
python train.py --config configs/APKDMBNV2-A1.yaml
python train.py --config configs/APKDMBNV2-L-02.yaml
python train.py --config configs/APKDMBNV2-L-20.yaml
python train.py --config configs/APKDMBNV2-L1-02.yaml 
python train.py --config configs/APKDMBNV2-L1-20.yaml
python train.py --config configs/APKDMBNV2-L2-02.yaml 
python train.py --config configs/APKDMBNV2-L2-20.yaml
python train.py --config configs/APKDMBNV2-L3-02.yaml 
python train.py --config configs/APKDMBNV2-L3-20.yaml
python train.py --config configs/APKDMBNV2-L4-02.yaml 
python train.py --config configs/APKDMBNV2-L4-20.yaml
